name: Deploy
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install step
        run: "bun install"

      - name: Build step
        run: "NITRO_PRESET=deno-deploy bun run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vpm-repos-syncronizer"
          entrypoint: "server/index.ts"
          root: ".output"
