name: Deploy to Deno

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    env:
      artifact_path: ${{ github.workspace }}/website-artifact

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: website-artifact
          path: ${{ env.artifact_path }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts

      - name: Deploy to Deno
        run: deno deploy --prod --org ${{ secrets.DENO_ORG_ID }} --app ${{ secrets.DENO_PROJECT_ID }} --token ${{ secrets.DENO_API_TOKEN }} ${{ env.artifact_path }}
        shell: bash
