name: Deploy To Deno Deploy
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: "corepack enable"

      - name: Install step
        run: "yarn install"

      - name: Build step
        run: "NITRO_PRESET=deno-deploy yarn run build"
        env:
          DISABLE_NUXT_HUB: "true"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "vpm-repos-syncronizer"
          entrypoint: "server/index.ts"
          root: ".output"
