name: Deploy to EdgeOne

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    env:
      artifact_path: ${{ github.workspace }}/website-artifact

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: website-artifact
          path: ${{ env.artifact_path }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Deploy to EdgeOne
        run: bunx edgeone pages deploy $artifact_path -n ${{ secrets.EDGEONE_PROJECT_NAME }} -t ${{ secrets.EDGEONE_API_TOKEN }}
        shell: bash